name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build binaries for all platforms
        run: make build
        env:
          VERSION: ${{ github.ref_name }}

      - name: Generate release notes
        run: |
          echo "## Changes" > release_notes.md
          echo "" >> release_notes.md
          echo "### Installation" >> release_notes.md
          echo "" >> release_notes.md
          echo "#### Go Install" >> release_notes.md
          echo '```bash' >> release_notes.md
          echo "go install github.com/kborovik/gcp-iam@${{ github.ref_name }}" >> release_notes.md
          echo '```' >> release_notes.md
          echo "" >> release_notes.md
          echo "#### Download Binary" >> release_notes.md
          echo "Download the appropriate binary for your platform from the assets below." >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
